### ISSUE TITLE
Design enhancements create event

### ISSUE THREAD

**Issue by tavi004** [Inevio/GoogleCalendar#25]
- [ ] The hole input should be clickable and to drop down the calendar, the "up&down" arrow and the other one shouldn't be there because it's wasted space ![image](https://user-images.githubusercontent.com/3248361/35675725-6ac7c532-0749-11e8-9858-f01d8eb3d3be.png)

- [ ] Change the select icon: ![select](https://user-images.githubusercontent.com/3248361/35675790-a2518088-0749-11e8-9813-3eaa1ffb30ee.png)![select 2x](https://user-images.githubusercontent.com/3248361/35675791-a269ecc2-0749-11e8-993c-025ba37b7207.png)![image](https://user-images.githubusercontent.com/3248361/35675815-b3784112-0749-11e8-9eb3-615b810ef8c4.png)

- [x] When you open the create event view the date and time should be the current ones not (dd/mm/yyyy and --:--)

**Comment by umair-brainx** [comment]
Fixed the third part. I already mentioned in estimations that we can't do the 1st and 2nd part of this issue.

**Comment by jorge9200** [comment]
Sometimes it doesnt show properly
![image](https://user-images.githubusercontent.com/8724844/36415901-cb14850a-1627-11e8-95bf-68163aaf8d42.png)

**Comment by umair-brainx** [comment]
Its because you have asked me to make its width fix according to your design i.e in fact smaller than actual width of date and time picker.

If we made the width to actual width of date and time picker it will be like this.
![screen shot 2018-02-20 at 2 29 16 pm](https://user-images.githubusercontent.com/26704318/36416350-a72c9420-164a-11e8-9ce8-48ba15e244da.png)
