### ISSUE TITLE
Making clearer the current day you're in

### ISSUE THREAD

**Issue by tavi004** [Inevio/GoogleCalendar#39]
- [ ] On the minicalendar on the sidebar is not very clear on which day you're in. Could we change it like on the google calendar page? Make the current day with a red box #e84c44
![image](https://user-images.githubusercontent.com/3248361/37825409-014b1ce4-2e90-11e8-97e0-9f54774d7a93.png)

- [ ] And for the month view we should make the current day number red also
and the font is not correct, it should be 13px and with a border around the square. color #666666 for the border
![image](https://user-images.githubusercontent.com/3248361/37783925-f529564a-2df6-11e8-85c7-c2e52793b0c3.png)

On the PSD looked like this: with the border and 13px font
![image](https://user-images.githubusercontent.com/3248361/37783977-1bbfd4a0-2df7-11e8-947a-9c67f7feae5b.png)

**Comment by umair-brainx** [comment]
Fixed. 
Could we change it like on the google calendar page? Make the current day with a red box #e84c44 **[DONE]**

we should make the current day number red also
and the font is not correct, it should be 13px **[DONE]**

Although we can't have the border around current day in month view due to plugin restriction.
